/*
 * Equipment Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Text.Json.Serialization;

namespace IO.Swagger.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class Dept : IEquatable<Dept>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember]
        [JsonPropertyName("id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets DivisionType
        /// </summary>
        [DataMember]
        [JsonPropertyName("division_type")]
        public string DivisionType { get; set; } = string.Empty;

        /// <summary>
        /// Gets or Sets DeptCode
        /// </summary>
        [DataMember]
        [JsonPropertyName("dept_code")]
        public string DeptCode { get; set; } = string.Empty;

        /// <summary>
        /// Gets or Sets DeptName
        /// </summary>
        [DataMember]
        [JsonPropertyName("dept_name")]
        public string DeptName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or Sets SortKey
        /// </summary>
        [DataMember]
        [JsonPropertyName("sort_key")]
        public int? SortKey { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember]
        [JsonPropertyName("note")]
        public string Note { get; set; } = string.Empty;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Dept {\n");
            sb.Append("  Id: ").Append(Id).Append('\n');
            sb.Append("  DivisionType: ").Append(DivisionType).Append('\n');
            sb.Append("  DeptCode: ").Append(DeptCode).Append('\n');
            sb.Append("  DeptName: ").Append(DeptName).Append('\n');
            sb.Append("  SortKey: ").Append(SortKey).Append('\n');
            sb.Append("  Note: ").Append(Note).Append('\n');
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        public override bool Equals(object? obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Dept)obj);
        }

        /// <summary>
        /// Returns true if Dept instances are equal
        /// </summary>
        public bool Equals(Dept? other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    (Id != null && Id.Equals(other.Id))
                ) &&
                (
                    DivisionType == other.DivisionType ||
                    (DivisionType != null && DivisionType.Equals(other.DivisionType))
                ) &&
                (
                    DeptCode == other.DeptCode ||
                    (DeptCode != null && DeptCode.Equals(other.DeptCode))
                ) &&
                (
                    DeptName == other.DeptName ||
                    (DeptName != null && DeptName.Equals(other.DeptName))
                ) &&
                (
                    SortKey == other.SortKey ||
                    (SortKey != null && SortKey.Equals(other.SortKey))
                ) &&
                (
                    Note == other.Note ||
                    (Note != null && Note.Equals(other.Note))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 41;
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (DivisionType != null)
                    hashCode = hashCode * 59 + DivisionType.GetHashCode();
                if (DeptCode != null)
                    hashCode = hashCode * 59 + DeptCode.GetHashCode();
                if (DeptName != null)
                    hashCode = hashCode * 59 + DeptName.GetHashCode();
                if (SortKey != null)
                    hashCode = hashCode * 59 + SortKey.GetHashCode();
                if (Note != null)
                    hashCode = hashCode * 59 + Note.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Dept? left, Dept? right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Dept? left, Dept? right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}